CC = gcc
CFLAGS = -g

default: all

all: merge wordCount heapSort
merge: merge.c
	${CC} ${CFLAGS} -o merge merge.c
wordCount: wordCount.c
	${CC} ${CFLAGS} -o wordCount wordCount.c
heapSort: heapSort.c
	${CC} ${CFLAGS} -o heapSort heapSort.c