CC = gcc
CFLAGS = -g

default: all

all: averageScores vowelCount stringReplace
stars: averageScores.c
	${CC} ${CFLAGS} -o averageScores averageScores.c
hollowStars: vowelCount.c
	${CC} ${CFLAGS} -o vowelCount vowelCount.c
stringReplace: stringReplace.c
	${CC} ${CFLAGS} -o stringReplace stringReplace.c
